- grama/plot_auto.py
tweaked autoplot functionality to print delegated function; changed a couple delegate fcn names; exposed delegated plotters
> Dev plt select

- grama/comp_building.py
- grama/comp_metamodels.py
- grama/core.py
- grama/eval_defaults.py
- grama/eval_random.py
- grama/fit/fit_scikitlearn.py
- grama/plot_auto.py
- grama/tools.py
- grama/tran_summaries.py
- grama/tran_tools.py
Add to documentation; rename a couple plot functions
> refine documentation & rename some plotters

- grama/dfply/reshape.py
- tests/test_dfply_reshape.py
> Dev spread fill

- grama/comp_building.py
- grama/comp_metamodels.py
- grama/eval/eval_pyDOE.py
- grama/eval_defaults.py
- grama/eval_opt.py
- grama/eval_random.py
- grama/eval_tail.py
- grama/fit/fit_lolo.py
- grama/fit/fit_scikitlearn.py
- grama/fit/fit_statsmodels.py
- grama/fit_synonyms.py
- grama/plot_auto.py
- grama/tools.py
- grama/tran/tran_matminer.py
- grama/tran/tran_scikitlearn.py
- grama/tran/tran_umap.py
- grama/tran_shapley.py
- grama/tran_summaries.py
- grama/tran_tools.py
fixes documentation for grama verbs
> Fix pipe doc

- grama/comp_building.py
- grama/core.py
- grama/fit_synonyms.py
- tests/test_core.py
- tests/test_fit.py
Add parametric UQ capability to fit_nls()
> Dev fit nls linpool

- grama/eval_opt.py
- grama/fit_synonyms.py
- tests/test_evals.py
add random restart capability to fit_nls / eval_nls; fixes to fixed variable models
> Fix nls restart fix

- grama/models/trajectory_linear_drag.py
- tests/test_fit.py
add a bound for `t` to set nominal conditions; add linear trajectory fitting as unittest
> Fix trajectory bounds

- grama/fit_synonyms.py
- tests/test_fit.py
Add a warning to fit_nls when model is detected to be unidentifiable
> Dev fit check idet

- grama/dfply/summary_functions.py
removes core statsmodels dependency by re-implementing binomial_ci using Wilson's method
> reimplement binomial_ci to remove statsmodels

- grama/mutate_helpers.py
- tests/test_dfply_mutate_helpers.py
Add Pareto frontier calculator
> Dev pareto min

- grama/eval_opt.py
- setup.py
- tests/test_evals.py
For eval_min add leq constraints; multiple restarts; improve documentation
> Dev min features

- grama/eval_tail.py
- tests/test_tail.py
flatten output when setting append=False
> Dev form flat

- grama/fit/fit_scikitlearn.py
- tests/test_fit.py
add predictive uncertainties (standard deviation) to gp fitting routine
> Dev gp std

- grama/tran/tran_scikitlearn.py
- tests/test_transforms.py
> Dev poly feat

- grama/eval_tail.py
- tests/test_tail.py
Found bug in FORM implementation; MPP was returned in Z-space. Fixed to return point in natural space; added unittest to confirm
> Fix form transform

- grama/fit/fit_lolo.py
- grama/fit/fit_scikitlearn.py
- grama/tran_tools.py
- tests/test_fit.py
standardize fitting routines to add a suffix; modify tran_kfolds to use suffix
> Dev fitting kfold

- grama/tran_tools.py
- tests/test_transforms.py
Add `tran_md()` convenience function
> Dev tran md

- grama/eval_opt.py
- grama/fit_synonyms.py
- tests/test_evals.py
Allow user-specified initial parameter guesses with `df_init` in `eval_nls()`
> Dev eval nls init

- codecov.yml
> Create codecov.yml file to compute coverage over code base

- grama/comp_building.py
- grama/core.py
- grama/dfply/join.py
- grama/dfply/mask_helpers.py
- grama/dfply/reshape.py
- grama/dfply/select.py
- grama/dfply/set_ops.py
- grama/dfply/string_helpers.py
- grama/dfply/subset.py
- grama/dfply/summary_functions.py
- grama/dfply/vector.py
- grama/eval/eval_pyDOE.py
- grama/eval_defaults.py
- grama/eval_opt.py
- grama/eval_random.py
- grama/models/plane_laminate.py
- grama/tran_shapley.py
- tutorials/sep.py
Primarily removed unnecessary statements, such as else, elif, etc.
> Fixed more previously existing codefactors issues with the package.

- grama/tran_pivot.py
- tests/test_pivot.py
Changes:
-tran_select support for names_to argument
-names_sep argument added
-names_sep works with regex
-.value functionality added for names_to argument
> Updated Functionality added to Pivot_longer

- grama/dfply/summary_functions.py
- tests/test_dfply_summary_functions.py
Add `gr.skew()` and `gr.kurt()` summary functions for skewness and kurtosis.
> Dev skew kurt

- grama/marginals.py
- tests/test_marginals.py
Add `marg_mom` utility for method of moments distribution fitting
> Dev marg mom

- grama/models/circuit_RLC.py
- tests/test_models.py
> Fix prlc model

- grama/tools.py
- tests/test_tools.py
- tests/test_transforms.py
Implement `df_grid()` helper for variable sweeps
> Dev df grid

- grama/marginals.py
Add capability to fix distribution parameters and set initial guesses for distribution parameters in `marg_named()`; add documentation for these capabilities.
> Dev marginal init fix

- grama/marginals.py
- tests/test_marginals.py
Add random variable sample method to marginal `Marginal.r()`
> Dev marginal rvs

- grama/marginals.py
- tests/test_marginals.py
Add frozen `loc` parameter option to `marg_mom()` via `floc` argument
> Dev mom frozen loc

- grama/comp_building.py
- grama/eval_contour.py
- grama/eval_defaults.py
- grama/eval_random.py
- grama/plot_auto.py
- tests/test_autoplot.py
- tests/test_contour.py
Add plot_contour() helper for contour data, dispatch from plot_auto() with eval_contour()
> Dev plot contour

- grama/__init__.py
- grama/mutate_helpers.py
- grama/spc.py
- tests/test_spc.py
Implement basic statistical process tools: Xbar and S chart helper
> Dev spc tools

- grama/psdr/basis.py
- grama/psdr/domains/euclidean.py
- grama/psdr/local_linear.py
Remove all imports of `backports` package to avoid some dependency issues
> Fix psdr backports

- grama/dfply/mask_helpers.py
- grama/dfply/reshape.py
- grama/dfply/select.py
- grama/dfply/string_helpers.py
- grama/dfply/subset.py
- grama/dfply/summarize.py
- grama/dfply/summary_functions.py
- grama/dfply/transform.py
- grama/mutate_helpers.py
Improves / adds missing docstrings for various transform utilities.
> Dev dfply docstrings

- grama/dfply/summary_functions.py
- tests/test_dfply_summary_functions.py
Add implicit mode for `gr.n()`.
> Dev n implicit

- grama/fit_synonyms.py
- tests/test_fit.py
The `out` argument was ignored by `fit_nls()`; cover this with a unittest and fix.
> Fix fit nls out

- grama/fit_synonyms.py
Hotfix of Pandas-raised error passing a set to `columns` argument in `DataFrame()`
> Fix colset

- grama/eval_defaults.py
- tests/test_evals.py
Add linear uncertainty propagation tool: Approximates the variance of model outputs using a linear approximation
> Dev eval linup

- grama/core.py
- tests/test_core.py
Dynamically switch the units of runtime estimates for readability.
> Dev runtime units

- grama/comp_building.py
- tests/test_mbi.py
Allow DataFrame input for `gr.cp_freeze()`
> Dev freeze df

- grama/core.py
- grama/eval_defaults.py
- grama/eval_random.py
- tests/test_core.py
Enable adaptive runtime message; switches units based on runtime magnitude.
> Fix runtime msg

- grama/tran_pivot.py
- setup.py
lock pandas version to (temporarily) fix pivot_wider
> version lock pandas to fix pivot_wider

- grama/fit/fit_lolo.py
- tests/test_fit.py
Deprecate lolo; remove unit test for fit_lolo, note deprecation in docstring
> Deprecate lolo & fix numpy version issue

- grama/fit_synonyms.py
- tests/test_fit.py
Discovered an error in fit_nls() created by change to cp_function(). Created a unittest to cover this, and fixed the error.
> Fix nls fixedvals

- grama/marginals.py
- tests/test_marginals.py
Add bounded distribution specification for `gr.marg_mom` with uniform and beta marginals.
> Dev mom bounded
